Fix Guzzle error processing with http_errors=true
guzzle/command pull request #44
Opened 2021-11-03 21:32 UTC by savchukoleksii

When Guzzle option http_errors=true this errorResponses not processing and this code skipped during exception:
`yield $this->transformResponseToResult($response, $request, $command);`
This fix allow errorResponses mappings from Description. 
If error not found in errorResponses than Guzzle error will propagate.

2021-11-03 22:06 UTC, GrahamCampbell requested changes

2021-11-03 22:06 UTC, GrahamCampbell commented on .gitignore
> +.idea/
please put this in your global .gitignore file instead

2021-11-04 23:44 UTC, savchukoleksii commented
@GrahamCampbell 
Done

2021-11-05 09:01 UTC, GrahamCampbell commented
Could you add a unit test please? Then I'll be happy to merge.

2021-11-26 18:38 UTC, savchukoleksii commented
@GrahamCampbell sorry, have not time for continue this pr. Can you help me with tests?

2023-04-18 08:14 UTC, closed without merging

2023-04-18 08:14 UTC, GrahamCampbell commented
I don't have any capacity for this. I think we just need to say that that we require people not use that mode.